### ISSUE TITLE
Missing descriptions

### ISSUE THREAD

**Issue by eidolon232** [SCARaw/Arcanum-Item-Description-Project#28]
Shakar Offering:  Reaper's Axe (Alternative to Bone Dagger)
Torg Offering: Any Ruby gem or Ruby jewelry
Bolo Offering: Any ring (it might get confusing if you start tagging every single ring in the game)
Skull of the Twins: Quest item
Blade of Xerxes: Quest item

**Comment by SCARaw** [comment]
Thanks, we can not change everything yet and axes are tight on real estate

1.  Torg Offering: Any Ruby gem or Ruby jewelry - this can lead to some errors and makes rubies look better than other gems
2. same reason as the Rubies due to overwhelming number of variant rings current versions of the work will not change them

as for 2 last items:
i simply could not find them
which means they are not on the proto list for item_effect.mes

**Comment by SCARaw** [comment]
{6070}{D:1-12(+10 Undead) FT:1-9 MSR:8/10 [Chop]} Reaper's Axe

This is our current description for the axe
it takes 41 characters, it might fit [Offering], but than we have to forget about MC
i will run the test in the game how it looks and if it fits and cameback

**Comment by SCARaw** [comment]
it fits, but no MC
![image](https://github.com/user-attachments/assets/78d5f46c-c43c-41d0-92a3-a1cd000e7f70)
i will change it for now, but if we found more properties for it i can't promisse it will stay

**Comment by Barbarbrick** [comment]
> as for 2 last items: i simply could not find them which means they are not on the proto list for item_effect.mes

The names of some quest items are in the `gamedesc.mes` and their descriptions are in the `gameitemeffect.mes`. Both of those files are in the `/Arcanum/modules/Arcanum.PATCH1`. You can extract them using [dbmaker.exe](https://terra-arcanum.com/downloads/arcanum/tools/dbmaker.zip) or [datbuilder](https://terra-arcanum.com/downloads/arcanum/tools/DATBuilder.zip).

Actually, _Blade of Xerxes_ is only in the `gamedesc.mes`, so you probably should make a new entry for it in the `gameitemeffect.mes`. To complicate things, in the game there are [two versions](https://arcanum.fandom.com/wiki/Daggers#Blade_of_Xerxes) of that item, with different stats, depending on how you obtain it.

After modifying `gamedesc.mes` and `gameitemeffect.mes`, you can make a new patch with subsequent number `Arcanum.PATCH2`. Simply place them in `/mes` folder and run:

```
 dbmaker.exe -r Arcanum.PATCH2 mes\* 
```
Then copy `Arcanum.PATCH2` to the `/Arcanum/modules/`.

**Comment by SCARaw** [comment]
we are currently working on the variants and this hard to edit files
blade of xerxes is not big deal, one version just have TH +5
our current problem is giant scope of files to cover in variant lists
and find all the items that lie about their own stats
